### ISSUE TITLE
Not possible to install on 20GB disk

### ISSUE THREAD

**Issue by vermaden** [arisblubsd/arisblu-livecd#1]
Check this thread:

https://twitter.com/vermaden/status/1326600540093112323

Regards.

**Comment by vermaden** [comment]
Some debug:

```
% sh -x /usr/local/bin/freebsd-install
```

https://twitter.com/vermaden/status/1326604677706821635/photo/1

**Comment by KaiLikesLinux** [comment]
Installation tool has been deleted, we will look into adding an installation tool of other forms
