### ISSUE TITLE
Application issues

### ISSUE THREAD

**Issue by KaiLikesLinux** [arisblubsd/arisblu-livecd#2]
## Some Applications do not work as they should

Bugged Application List:
- [ ] Installation tool
- [ ] Configure WiFi
- [ ] Create LiveUSB
- [ ] Configure XORG

### Installation Tool
See #1; 
- Probably issue with other executables
- Fix ASAP

### Configure WiFi
- Does not open
- WiFi cannot be configured

### Create LiveUSB
- Complains about WiFi connvection
- Required fix

### Configure XORG
- Does not open
- Not important for next release

**Comment by KaiLikesLinux** [comment]
Turns out files were not executable. See [this commit change](https://github.com/arisblubsd/arisblu-livecd/commit/67437770082b815a2ee79ef53dfdcf81a649e82a)

**Comment by KaiLikesLinux** [comment]
Discovered what line of code is giving this issue. In the [arisblu-wifi-tool](https://github.com/arisblubsd/arisblu-livecd/blob/master/overlays/uzip/arisblu-wifi-tool/files/usr/local/bin/arisblu-wifi-tool) lines 82 to 85. Something in these lines of code is causing an issue. 

These lines of code are an if statement, and so if we figure out why this is not working we can then fix the WiFi tool and get everything else working. The lines of code go as followed.

```sh
if [ "$?" -eq 0 ] && [ -z "${wnic}" ] ; then
  warning "No wlan devices found"
  exit 0
fi
```

I will need to look into what $? should output. Also ${wnic} is *"wnic=$(get_wireless)"*.

It might be an issue with get_wireless being outdated or wrong as FuryBSD last used 12.0 and this runs under 12.2 and there might be a difference in how wireless functions work. I could be wrong but I am not 100% sure of the differences between them. One fix we could do is go back to 12.0 but that seems like a non-issue to me.

**Comment by KaiLikesLinux** [comment]
We will see in 24 hours on if we will be going back to 12.0 or sticking with 12.2 which will change how we handle this issue

https://twitter.com/ArisbluBSD/status/1326658981033463808

**Comment by KaiLikesLinux** [comment]
For the FreeBSD installer, in [freebsd-install.py](https://github.com/arisblubsd/arisblu-livecd/blob/master/overlays/uzip/freebsd-installer/files/usr/local/share/data/freebsd-install/freebsd-install.py) lines 688 to 702 define the error given by the installer. We can look into why this is happening and make any and all changes as needed.

**Comment by KaiLikesLinux** [comment]
![image](https://user-images.githubusercontent.com/62919224/100521770-e72d6500-3162-11eb-9e8a-1913ada5f992.png)

I wonder if the WiFi tool cannot discover disks at em0 and needs to be modified to do so?

**Comment by grahamperrin** [comment]
AFAIK wpa_gui is strictly for wireless.

**Comment by KaiLikesLinux** [comment]
Hmm, well then, I am not 100% sure what the plan should be to fix this. Especially since there are still important discussions to be made in the background.

**Comment by KaiLikesLinux** [comment]
```py
def initializePage(self):
        print("Displaying DiskPage")

        wizard.required_mib_on_disk = self.getMiBRequiredOnDisk()
        self.disk_listwidget.clearSelection()  # If the user clicked back and forth, start with nothing selected
        self.periodically_list_disks()

        if wizard.required_mib_on_disk < 4:
            self.timer.stop()
            wizard.showErrorPage("The installer script did not report the required disk space. Are you running the installer on a supported system? Can you run the installer script with sudo without needing a password?")
            self.disk_listwidget.hide()  # FIXME: Why is this needed? Can we do without?
            return

        print("Disk space required: %d MiB" % wizard.required_mib_on_disk)
        self.label.setText("Disk space required: %s MiB" % wizard.required_mib_on_disk)
```

Something about these lines of code is problematic. Line 688 to 702 from [freebsd-install.py](https://github.com/arisblubsd/arisblu-livecd/blob/master/overlays/uzip/freebsd-installer/files/usr/local/share/data/freebsd-install/freebsd-install.py).

It  does mention a function, lines 659 to 686
```py
def getMiBRequiredOnDisk(self):
        # _, space_used_on_root_mountpoint, _ = shutil.disk_usage("/")
        # return int(float(space_used_on_root_mountpoint * 1.3))
        proc = QtCore.QProcess()
        command = 'sudo'
        args = ["-n", "-E", wizard.installer_script]  # -E to pass environment variables into the command ran with sudo
        env = QtCore.QProcessEnvironment.systemEnvironment()
        env.insert("INSTALLER_PRINT_MIB_NEEDED", "YES")
        proc.setProcessEnvironment(env)
        try:
            print("Starting %s %s" % (command, args))
            proc.start(command, args)
        except:
            return 0
        proc.waitForFinished()
        output_lines = proc.readAllStandardOutput().split("\n")

        mib = 0
        for output_line in output_lines:
            print(str(output_line))
            if "INSTALLER_MIB_NEEDED=" in str(output_line):
                mib = int(output_line.split("=")[1])
                print("Response from the installer script: %i" % mib)
                correction_factor = 1.5  # FIXME: Correction factor due to compression differences
                adjusted_mib = int(mib * correction_factor)
                print("Adjusted MiB needed: %i" % adjusted_mib)
                return adjusted_mib
        return 0
```

Not sure what is going on but it needs to be fixed.

**Comment by KaiLikesLinux** [comment]
![image](https://user-images.githubusercontent.com/62919224/101261584-b797d300-36f5-11eb-9b26-17dfb65ddbba.png)
This is the terminal running the application. I want to test something but I wanted to post this first just in case.

**Comment by KaiLikesLinux** [comment]
Looks to be an issue in the [furybsd-install](https://github.com/arisblubsd/arisblu-livecd/blob/master/overlays/uzip/freebsd-installer/files/usr/local/bin/furybsd-install) shell script

**Comment by bsdlme** [comment]
> Discovered what line of code is giving this issue. In the [arisblu-wifi-tool](https://github.com/arisblubsd/arisblu-livecd/blob/master/overlays/uzip/arisblu-wifi-tool/files/usr/local/bin/arisblu-wifi-tool) lines 82 to 85. Something in these lines of code is causing an issue. 
> 
> These lines of code are an if statement, and so if we figure out why this is not working we can then fix the WiFi tool and get everything else working. The lines of code go as followed.
> 
> ```sh
> if [ "$?" -eq 0 ] && [ -z "${wnic}" ] ; then
>   warning "No wlan devices found"
>   exit 0
> fi
> ```
> 
> I will need to look into what $? should output. Also ${wnic} is *"wnic=$(get_wireless)"*.
> 

I think if you use "$?" it is treated as a string and -eq expects an integer.

**Comment by KaiLikesLinux** [comment]
discovered the issue might be related to [disks.py](https://github.com/arisblubsd/arisblu-livecd/blob/master/overlays/uzip/freebsd-installer/files/usr/local/share/data/freebsd-install/disks.py) for the installer. Lines 78 to 104 are the lines that appear before the error executes.

**Comment by KaiLikesLinux** [comment]
still looks like this section of code is the issue:
```py
if wizard.required_mib_on_disk < 4:
            self.timer.stop()
            wizard.showErrorPage("The installer script did not report the required disk space. Are you running the installer on a supported system? Can you run the installer script with sudo without needing a password?")
            self.disk_listwidget.hide()  # FIXME: Why is this needed? Can we do without?
            return
```

going to add a print statement to see what the output is

**Comment by KaiLikesLinux** [comment]
![image](https://user-images.githubusercontent.com/62919224/101419430-38e59600-38ad-11eb-9b74-9074ee8afe87.png)
The output is 0, which I think is bad

**Comment by KaiLikesLinux** [comment]
Goal for the next week: See what the heck HelloSystem does differently

**Comment by KaiLikesLinux** [comment]
We have decided to remove the applications causing issues
